spring.application.name=employeeMangaemnet

spring.datasource.url=jdbc:postgresql://localhost:5434/office?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Nikhi@123

#jpa every time as we run it update the changes
spring.jpa.hibernate.ddl-auto=update
#show all sql quries in log
spring.jpa.show-sql=true
#quries will be formated
#spring.jpa.properties.hibernate.format_sql=true
#
server.port=9090

#security
#spring.security.user.name=Admin
#spring.security.user.password=Admin123
#jwt.secretkey=iuswye3498hjred90qujfj
